### ISSUE TITLE
onClose not specified in 'Lightbox'

### ISSUE THREAD

**Issue by GregTheGreek** [jossmac/react-images#115]
Came across your component today, looks really great! good job!
I tried using it based on your docs and ran into an issue, I get a failed proptypes issue:

> Warning: Failed propType: Required prop `onClose` was not specified in `Lightbox`.

**Steps to reproduce the behavior:**
All i did was follow your instructions given in the DOCS. 

<img width="474" alt="screen shot 2016-12-23 at 14 15 35" src="https://cloud.githubusercontent.com/assets/16929357/21460835/51270b1a-c91a-11e6-8bf8-16f9fb35d47d.png">

**Comment by fahd** [comment]
im having the same error.

**Comment by eek** [comment]
I think the problem here is not the framework by itself but the Docs, the Docs need to exmplaing that the Lightbox represents the open Lightbox not the before and after state.

That's why `isOpen` is required (to tell Lightbox to show the image or not to show the image), and that is why `onClose` is also required (on Clicking the X to have something change the isOpen state to false). Fixing these 2 things will also fix your issues.

**Comment by goldylucks** [comment]
@GregTheGreek @fahd did you define `this.closeLightBox` function?  
Otherwise it will be undefined and it's a required prop.

I'm sending a PR now with better docs as @eek pointed out they are not very informative

**Comment by jossmac** [comment]
@eek is correct. Thank you @goldylucks for offering to update the docs.

@GregTheGreek @fahd to see the sort of function you'd pass to `onClose`, `onClickNext` etc. please checkout the [Gallery component](https://github.com/jossmac/react-images/blob/master/examples/src/components/Gallery.js) used in the examples website.
