### ISSUE TITLE
Going back in browser while lightbox is active makes scrolling impossible

### ISSUE THREAD

**Issue by vaclav-zeman** [jossmac/react-images#179]
**Steps to reproduce the behavior:**
1. open a SPA website
2. open a specific page where the Lightbox is used (so we can go back without window reload)
3. open Lightbox
4. click browser back button or Android HW back button
5. the page is now unscrollable (because there's `overflow-y: hidden` on `<body>`)

**Bug:**
It looks like componentWillUnmount (which enables scroll again) is not being called in ScrollLock

**Comment by Vincedream** [comment]
@vaclav-zeman hey man, i also want to ask this problem,have you solve this problem?

**Comment by vaclav-zeman** [comment]
@Vincedream Yep, I've got an ugly workaround until this gets fixed. I have the react-images Lightbox wrapped in my own comp. and there I just added this to componentWillUnmount:
```
// ... is 'document' defined 
document.body.style = null

const stopProp = e => e.stopPropagation()

document.body.addEventListener('touchstart', stopProp, true)
document.body.addEventListener('touchmove', stopProp, true)
// ...
```

**Comment by jossmac** [comment]
@vaclav-zeman @Vincedream I'm sorry that you're having this issue.

**The bad news**

Unfortunately due to the implementation of `isOpen` the Lightbox component cannot take advantage of *all* react's lifecycle hooks.

**The good news**

In the rewrite of this package (see #199) this isn't a problem as the consumer actually renders the `<Modal />`component, or not,  rather than passing state onto `isOpen`.

* * *

I would love to get some feedback on the rewrite if you don't mind 🙃

**Comment by jossmac** [comment]
Related #113
