### ISSUE TITLE
In search of a replacement ❓ 

### ISSUE THREAD

**Issue by sethsnel** [jossmac/react-images#400]
As described on NPM and the Readme, it is clear we should not longer use this library.
Instead it is advised to switch to 'React Responsive Carousel'.

However this surrogate is missing the Modal functionality which is pretty neat in react-images.

Without building my own gallery with modal support.
Are there any known maintained carousel packages that also support Modals?

**Comment by joeyfigaro** [comment]
Here to ask the same thing. 👍🏻

**Comment by jossmac** [comment]
This package is a testament to the failure of monolithic solutions; you just can't meet everyone's requirements. I recommend composing the parts you need to fulfil _your specific requirements_, rather than reaching for a "complete" solution.

Here's some **accessible** modal dialogs for React, that are style agnostic:
- [Reach UI dialog](https://reach.tech/dialog)
  - The folks behind React Router
- [Radix UI dialog](https://www.radix-ui.com/docs/primitives/components/dialog)
  - The front-end logic and behaviour behind [Modulz](https://www.modulz.app/)
- [Headless UI dialog](https://headlessui.dev/react/dialog)
  - Promising up-and-coming "headless" UI library for React
